name: bayesian-learning
channels:
  - conda-forge
  - defaults
  - pytorch-nightly
dependencies:
  - python=3.12
  - pandas
  - scikit-learn
  - pip
  - pyro-ppl
  - numpy
  - scapy
  - pgmpy
  - scikit-learn
  - seaborn
  - matplotlib
  - pygraphviz
  - daft-pgm
  - networkx
